"""empty message

Revision ID: bec220a2df0e
Revises: 4eb4eb88161a
Create Date: 2021-08-31 16:14:57.544347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec220a2df0e'
down_revision = '4eb4eb88161a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('new', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
